### PR TITLE
Enhance `UpdateArgumentIfMatch` logic

### PR DESCRIPTION
**Pull request by wplong11**
Enhance `UpdateArgumentIfMatch` logic by adding break statements. 😀

### CODE REVIEW

**Comment by gyuwon** [comment]
`master` branch updated after this pull request had made, so please rebase the work branch before merge.

**Comment by gyuwon** [comment]
You seem to merged `upstream/master` to your work branch instead rebase. Please follow these steps to rebase your work branch onto `upstream/master`

1. Reset your `master` to [`3cdf48f234fcae2be93bc7d9c715751834840741` commit](https://github.com/AutoReviser/AutoReviser/commit/3cdf48f234fcae2be93bc7d9c715751834840741)
   ```
   > git checkout master
   > git reset --hard 3cdf48f234fcae2be93bc7d9c715751834840741
   ```

1. Reset your work branch
   ```
   > git checkout enhance-update-argument-if-match
   > git reset --hard head~1
   ```

1. Rebase your work branch onto master
   ```
   > git rebase master
   ```

1. Push your work branch

**Comment by wplong11** [comment]
I fixed it. Thank you for guide 🙏

**Comment by gyuwon** [comment]
Thanks for you contribution! 👍

**Pull request merged**
